backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: '[skip ci] Upload "{{path}}"'
    deleteMedia: '[skip ci] Delete "{{path}}"'

publish_mode: editorial_workflow
display_url: https://andrewmmc.com
logo_url: https://andrewmmc.com/admin/logo.svg
media_folder: static/images
public_folder: /static

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    path: '{{year}}/{{title}}/{{slug}}'
    slug: 'index'
    media_folder: ''
    public_folder: ''
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Category', name: 'category', widget: 'list', required: false, default: [] }
      - { label: 'Canonical', name: 'canonical', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
    sortableFields: ['date']
  - name: 'notes'
    label: 'Notes'
    folder: 'content/notes'
    create: true
    path: '{{year}}/{{title}}/{{slug}}'
    slug: 'index'
    media_folder: ''
    public_folder: ''
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'notes-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Category', name: 'category', widget: 'list', required: false, default: [] }
      - { label: 'Body', name: 'body', widget: 'markdown' }
    sortableFields: ['date']
  - name: 'projects'
    label: 'Projects'
    folder: 'content/projects'
    create: true
    path: '{{year}}/{{title}}/{{slug}}'
    slug: 'index'
    media_folder: ''
    public_folder: ''
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'projects-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'featuredImage', widget: 'image', allow_multiple: false }
      - { label: 'Category', name: 'category', widget: 'list', required: false, default: [] }
      - { label: 'Body', name: 'body', widget: 'markdown' }
    sortableFields: ['date']
    
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'content/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }